language: node_js
node_js:
  - '4'

sudo: required

services:
  - docker

before_script:
  - sleep 5
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/ray-gym
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
